# Generated by Django 5.1.5 on 2025-04-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mokhkharazmy', '0002_customer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
