# Generated by Django 5.1.5 on 2025-04-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokhkharazmy', '0003_remove_product_description_remove_product_is_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=True, null=True, upload_to='upload/product/'),
        ),
    ]
