# Generated by Django 5.1.5 on 2025-04-27 17:31

import mokhkharazmy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokhkharazmy', '0004_remove_product_image_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=mokhkharazmy.models.Product.upload_to),
        ),
    ]
