# Generated by Django 5.1.5 on 2025-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokhkharazmy', '0005_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=True, null=True, upload_to='upload/product/'),
        ),
    ]
