# Generated by Django 5.1.5 on 2025-05-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mokhkharazmy', '0007_product_link_alter_product_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='link',
            new_name='product_link',
        ),
    ]
