# Generated by Django 5.1.5 on 2025-05-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mokhkharazmy', '0008_rename_link_product_product_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_link',
        ),
    ]
